// スマセン形式の列名を左から順に並べた配列

export const SmartSenkyoCompanyColumnNames: string[] = [
	"delete",
	"update",
	"import_number",
	"name",
	"kana",
	"rank",
	"memo",
	"company_zipcode",
	"company_prefecture",
	"company_address1",
	"company_address2",
	"company_address3",
	"company_address4",
	"company_address5",
	"send_type",
	"company_zipcode2",
	"alt_company_prefecture",
	"alt_company_address1",
	"alt_company_address2",
	"alt_company_address3",
	"alt_company_address4",
	"alt_company_address5",
	"company_tel",
	"company_tel2",
	"company_fax",
	"email",
	"company_url",
]
